web_server:
  bind: 0.0.0.0
  port: 3539
  web_ui: yes
  base_url: /flexget
tasks:
  new_anime:
    rss: https://nyaa.si/?page=rss
    series:
      # Monday
      - Shinmai Renkinjutsushi no Tenpo Keiei: {from_group: SubsPlease, quality: 720p}
      # Tuesday
      - Chainsaw Man: {from_group: SubsPlease, quality: 720p}
      # Wednesday
      - Tensei Shitara Ken Deshita: {from_group: SubsPlease, quality: 720p} 
      - Kage no Jitsuryokusha ni Naritakute!: {from_group: SubsPlease, quality: 720p}
      - Do It Yourself!!: {from_group: SubsPlease, quality: 720p}
      # Thursday
      - Akiba Maid Sensou: {from_group: SubsPlease, quality: 720p}
      # Friday
      # Saturday
      - Spy x Family: {from_group: SubsPlease, quality: 720p}
      - Bocchi the Rock!: {from_group: SubsPlease, quality: 720p}
      - Blue Lock: {from_group: SubsPlease, quality: 720p} 
      - Boku no Hero Academia: {from_group: SubsPlease, quality: 720p}
      - Beast Tamer: {from_group: SubsPlease, quality: 720p}
      - "Berserk - The Golden Age Arc Memorial Edition": {from_group: SubsPlease, quality: 720p}
      # Sunday
      - Fuufu Ijou, Koibito Miman: {from_group: SubsPlease, quality: 720p}
      - Fumetsu no Anata e S2: {from_group: SubsPlease, quality: 720p}
    download: /mnt/HDD/shared/torrents
schedules:
  - tasks: new_anime
    interval:
      minutes: 15
